### PR TITLE
fix(package.json): remove rxjs from peer deps

### PR DESCRIPTION
**Pull request by tupe12334**
we don't need the rxjs as peer dep because it comes with nestjs

### CODE REVIEW

**Comment by tupe12334** [comment]
@tienne can you see the pr and publish it as a new patch version?

**Comment by tienne** [comment]
[new patch version 0.1.6](https://github.com/codebrewlab/nestjs-storage/releases/tag/0.1.6)
thanks

**Comment by tienne** [comment]
Is it okay to close the issue?

**Comment by tupe12334** [comment]
@tienne yes

**Comment by tienne** [comment]
@tupe12334 thanks

**Pull request closed without merging**
